# Common software that I need installed when setting up a new Mac
#
# install this stuff by running `brew bundle` after homebrew is installed
#
cask "aerial"
cask "docker"
cask "chrome"
cask "flux"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "iterm2"
cask "kindle"
cask "menumeters"
cask "metabase"
cask "ngrok"
cask "spotify"
cask "homebrew/cask-drivers/qmk-toolbox"
tap "railwaycat/emacsmacport"
tap "aws/tap"
brew "ag"
brew "awscli"
brew "elixir"
brew "emacs-mac", args: ["with-modern-icon" "with-natural-title-bar"]
brew "git"
brew "git-extras"
brew "httpie"
brew "hugo"
brew "keychain"
brew "leiningen"
brew "postgresql"
brew "aws-sam-cli"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# untested
# cask "dropbox"
