# Common software that I need installed when setting up a new Mac
#
# install this stuff by running `brew bundle` after homebrew is installed
#
tap "homebrew/cask-fonts"
cask "aerial"
cask "docker"
cask "flux"
cask "font-fira-code"
cask "iterm2"
cask "kindle"
cask "menumeters"
cask "metabase"
cask "ngrok"
cask "spotify"
tap "railwaycat/emacsmacport"
brew "ag"
brew "dbmate"
brew "elixir"
brew "emacs-mac", args: ["with-modern-icon", "with-natural-title-bar"]
brew "git"
brew "git-extras"
brew "httpie"
brew "hugo"
brew "keychain"
brew "leiningen"
brew "postgresql"
brew "pyenv"
brew "nodenv"
brew "rbenv"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# untested
# cask "dropbox"
